name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    container: quay.io/qiime2/tiny:2026.7
    steps:
      - uses: actions/checkout@v4
      - name: Install and test
        shell: bash
        run: |
          conda run --name rachis-tiny-2026.7 python -m pip install pytest ruff
          conda run --name rachis-tiny-2026.7 python -m pip install -e . --no-deps --no-build-isolation
          conda run --name rachis-tiny-2026.7 python -m pytest
          conda run --name rachis-tiny-2026.7 ruff check .
